### ISSUE TITLE
Decide on a tech stack

### ISSUE THREAD

**Issue by JakobTopholt** [TimMo-dev/P7#41]
We should settle on a tech stack some suggestions might be:

Typescript, nodeJS, MySQL, using AAU for hosting and using Llama as the LLM of choice.

- [x] Front end chosen #44
- [x] Back end chosen  #45 
- [x] Database chosen #42 
- [ ] Hosting chosen #47 
- [x] LLM chosen #43 
- [x] Testing Suite chosen #46
- [ ] Arguments for all written and documented
- [ ] Review

Related to #42 #43 #44 #45 #46 and #47

**Comment by TimMo-dev** [comment]
Hosting is currently irrelevant as of sprint 4
